#!/bin/bash
set -eEuo pipefail
cd "$(dirname "$(readlink -f "$0")")"

source bash-buddy/lib/trap_error_info.sh
source bash-buddy/lib/common_utils.sh

################################################################################
# prepare
################################################################################

source bash-buddy/lib/prepare_jdks.sh
source bash-buddy/lib/java_build_utils.sh

################################################################################
# codecov logic
################################################################################

cd ..

export DCM_AGENT_SUPPRESS_EXCEPTION_STACK=true

prepare_jdks::switch_to_jdk 11

if [ "${1:-}" = "-s" ]; then
  jvb::mvn_cmd -Pgen-code-cov jacoco:prepare-agent surefire:test jacoco:report
else
  jvb::mvn_cmd -Pgen-code-cov clean test
fi

prepare_jdks::switch_to_jdk 8
jvb::mvn_cmd -Pgen-code-cov jacoco:prepare-agent surefire:test jacoco:report coveralls:report

bash <(curl -s https://codecov.io/bash)
